### ISSUE TITLE
GitKraken not unleashed if it is not installed in /Applications

### ISSUE THREAD

**Issue by nerdgore** [danielbayley/atom-gitkraken#2] opened 2016-05-27 11:11 UTC
### The Problem
I am in a company setup and install software under `/Users/myname/Applications`. It looks like this plugin is set up to only look in `/Applications`. Therefore using any of the available commands to launch GitKraken from Atom has no result.

### The Solution
A more appropriate way would be to use the `open` command.

```
open -a GitKraken
```

This will open the appropriate application no matter where it is installed or what the actually app container name.

### Reference
See [OSXDaily: How to launch GUI Applications from the Terminal](http://osxdaily.com/2007/02/01/how-to-launch-gui-applications-from-the-terminal/) or `man open`.

**Comment by danielbayley** [comment] 2016-05-27 15:39
@nerdgore Actually `open -a` was the first thing I tried for the reason you give, but while doing it that way solves the problem of the application being installed in a non-standard location, it introduces the much more common problem of not actually opening the _current_ project as intended; only the last one you had open.

Taking into account other install locations would be nice, but that also raises the issue of making it work cross-platform (so Windows for example would be even more of a crapshoot as to where the app might actually be). Some kind of command line tool released with GitKraken would likely be the best solution, but doesn't exist at the moment.

**Comment by nerdgore** [comment] 2016-05-27 17:01
I see. The only thing I managed with `open` was opening a new instance with the provided path. I just played around with it for a few minutes but I couldn't really find documentation on what the command line parameters are. Maybe I am missing something.
```
open -n -b com.axosoft.GitKraken --args -p /path/to/repo
```

The atom command line tool also uses open but does a lot of extra work too:
```
 if [ -z "${ATOM_PATH}" ]; then
    # If ATOM_PATH isnt set, check /Applications and then ~/Applications for Atom.app
    if [ -x "/Applications/$ATOM_APP_NAME" ]; then
      ATOM_PATH="/Applications"
    elif [ -x "$HOME/Applications/$ATOM_APP_NAME" ]; then
      ATOM_PATH="$HOME/Applications"
    else
      # We havent found an Atom.app, use spotlight to search for Atom
      ATOM_PATH="$(mdfind "kMDItemCFBundleIdentifier == 'com.github.atom'" | grep -v ShipIt | head -1 | xargs -0 dirname)"

      # Exit if Atom can't be found
      if [ ! -x "$ATOM_PATH/$ATOM_APP_NAME" ]; then
        echo "Cannot locate Atom.app, it is usually located in /Applications. Set the ATOM_PATH environment variable to the directory containing Atom.app."
        exit 1
      fi
    fi
  fi
```

**Comment by danielbayley** [comment] 2016-05-27 17:18
@nerdgore Actually `open -b com.axosoft.GitKraken --args -p /path/to/repo` works well 👍 
I can quickly push it or do you want to do a PR?

**Comment by nerdgore** [comment] 2016-05-27 17:36
I can certainly open a PR but I couldn't get GitKraken to change the repo in the running instance. I always had to use the `-n` flag. I'll try again later today.

**Comment by danielbayley** [comment] 2016-05-27 18:07
> I couldn't get GitKraken to change the repo in the running instance.

With the `-n` flag it will open a new instance each time the `open` function is called, whereas _without_ the `-n` flag it will only produce one instance per project (much preferrable). I don't think it's possible to get the running instance to change repo unless the developers specifically add it. `[-]-p[ath]` is the only useful command line flag that _Electron_ (which GitKraken is built on) will accept in the meantime.

Iv'e gone ahead and implemented this anyway as I had some other tweaks to push. Nice one 👍

**Closed** 2016-05-27 18:06 UTC
Labels: enhancement

**Comment by nerdgore** [comment] 2016-05-30 06:50
Thanks, works like a charm!
