### ISSUE TITLE
Error instaling gitkraken on Atom with Ubuntu

### ISSUE THREAD

**Issue by edmgold** [danielbayley/atom-gitkraken#6] opened 2016-09-01 14:36 UTC
![atom gitkraken](https://cloud.githubusercontent.com/assets/13180716/18171395/39597e90-7038-11e6-8b39-85e62efd9af8.png)

Please help me with this error, please.

**Comment by danielbayley** [comment] 2016-12-11 17:32
@edmgold I think this must be what gets thrown when you try to install a package on an unsupported platform. See [package.json]… `"os": ["darwin"]`. Therefore this is effectively a duplicate of #3; keep an eye on that issue for when Linux support is added.

[package.json]: https://github.com/danielbayley/atom-gitkraken/blob/master/package.json#L22-L24

**Closed by danielbayley** 2016-12-11 17:32 UTC
